s = input('Digite algo: ')
print('o tipo primitivo desse valor é' , type(s))
print('1. É alfanumérico?' , s.isalnum())
#print(s.isalnum())
print('2. É formado apenas por letras?' , s.isalpha())
#print(s.isalpha())
print('3. É decimal?' , s.isdecimal())
#print(s.isdecimal())
print('4. Está todo em letra maiúscula?' , s.isupper())
#print(s.isupper())
print('5. Está todo em letra minúscula?' , s.islower())
#print(s.islower())
print('6. Só tem espaços?' , s.isspace())
print('7. É valor numérico?' , s.isnumeric())
print('8. Está capitalizada?' , s.istitle())
